// AUTO-GENERATED by scripts/gen_nts_genre_map.py — do not edit by hand.
// Maps the library's free-text Spotify genre tokens onto NTS's controlled
// top-level vocabulary (nts.live/api/v2/genres). Used to filter the track
// library by NTS genre. Exact taxonomy matches + a hand-map of the
// high-frequency residual. Keys are NTS top-genres; values are the raw
// lowercase tokens (as they appear in the Genres column) that roll up to it.

export const NTS_GENRES: string[] = [
  "ambient / new age",
  "electronica / downtempo",
  "hip-hop / r'n'b",
  "new club",
  "uk dance / grime",
  "house / techno",
  "post punk / new wave",
  "alternative rock / punk",
  "rock",
  "metal",
  "avant garde",
  "caribbean",
  "latin / brazilian",
  "jazz",
  "soul / rhythm & blues",
  "disco / boogie",
  "african / middle eastern",
  "asia",
  "classical / opera",
  "other",
];

export const NTS_GENRE_TOKENS: Record<string, string[]> = {
  "ambient / new age": ["ambient", "new age", "vaporwave"],
  "electronica / downtempo": ["chillstep", "chillwave", "downtempo", "electronica", "future bass", "glitch", "idm", "lo-fi", "lo-fi beats", "trip hop", "witch house"],
  "hip-hop / r'n'b": ["alternative hip hop", "boom bap", "cloud rap", "crunk", "drill", "east coast hip hop", "emo rap", "experimental hip hop", "g-funk", "hip hop", "jazz rap", "lo-fi hip hop", "melodic rap", "new jack swing", "old school hip hop", "rage rap", "rap", "southern hip hop", "trap", "trap soul", "underground hip hop", "west coast hip hop"],
  "new club": ["afro house", "afrobeats", "afropiano", "amapiano", "baltimore club", "bass", "brega", "club", "edm", "footwork", "gengetone", "gqom", "hyperpop", "jersey club", "kuduro", "ndombolo", "nightcore", "reggaeton", "singeli", "vinahouse"],
  "uk dance / grime": ["bass music", "bassline", "breakcore", "drum and bass", "drumstep", "dubstep", "grime", "jungle", "liquid funk", "uk funky", "uk garage", "uk grime"],
  "house / techno": ["acid house", "breakbeat", "chicago house", "deep house", "dub techno", "electro", "gabber", "happy hardcore", "hardstyle", "house", "jazz house", "lo-fi house", "melodic house", "melodic techno", "minimal techno", "tech house", "techno", "trance"],
  "post punk / new wave": ["ebm", "electroclash", "industrial", "new wave"],
  "alternative rock / punk": ["alternative rock", "art rock", "dream pop", "emo", "garage rock", "grunge", "hardcore punk", "indie", "indie rock", "math rock", "neo-psychedelic", "noise rock", "punk", "shibuya-kei", "shoegaze", "space rock"],
  "rock": ["classic rock", "country", "folk", "hard rock", "krautrock", "power pop", "psychedelic rock", "rock", "rockabilly", "soft rock", "yacht rock"],
  "metal": ["black metal", "death metal", "grindcore", "heavy metal", "metal", "metalcore", "nu metal"],
  "avant garde": ["dark ambient", "drone", "electroacoustic", "experimental", "musique concr\u00e8te", "plunderphonics"],
  "caribbean": ["calypso", "dancehall", "dembow", "dub", "lovers rock", "reggae", "rocksteady", "roots reggae", "shatta", "ska", "soca", "zouk"],
  "latin / brazilian": ["bachata", "bolero", "bossa nova", "champeta", "chicha", "corrido", "cumbia", "flamenco", "forr\u00f3", "freestyle", "guaracha", "latin jazz", "mariachi", "merengue", "norte\u00f1o", "nueva trova", "salsa", "samba", "tango", "vallenato"],
  "jazz": ["acid jazz", "ambient jazz", "bebop", "experimental jazz", "free jazz", "hard bop", "indie jazz", "jazz", "jazz beats", "jazz funk", "jazz fusion", "nu jazz", "soul jazz"],
  "soul / rhythm & blues": ["alternative r&b", "blues", "classic soul", "funk", "gospel", "indie soul", "motown", "neo soul", "quiet storm", "r&b", "retro soul", "soul"],
  "disco / boogie": ["boogie"],
  "african / middle eastern": ["afro r&b", "afrobeat", "afropop", "afroswing", "anatolian rock", "bikutsi", "ethiopian jazz", "gnawa", "highlife", "khaleeji", "kizomba", "mahraganat", "maloya", "ra\u00ef"],
  "asia": ["bangla pop", "bhangra", "bollywood", "budots", "c-pop", "city pop", "dangdut", "desi", "desi hip hop", "devotional", "ghazal", "hindi pop", "indian indie", "j-pop", "k-pop", "kannada pop", "kollywood", "kundiman", "luk thung", "malayalam pop", "marathi pop", "mollywood", "punjabi hip hop", "punjabi pop", "sufi", "tamil dance", "tamil hip hop", "tamil pop", "telugu pop", "tollywood", "v-pop"],
  "classical / opera": ["baroque", "chamber music", "classical", "minimalism", "opera"],
  "other": ["art pop", "baroque pop", "bedroom pop", "bhajan", "bluegrass", "chanson", "christmas", "pop", "qawwali", "soundtrack", "spoken word"],
};

// NTS episode/show genres arrive as subgenre objects whose id is
// `genres-<groupId>-<sub>`. This rolls a groupId up to its top-genre so the
// NTS tab and the track library share one set of filter chips.
export const NTS_GROUP_TO_TOP: Record<string, string> = {
  "ambientnewage": "ambient / new age",
  "electronicadowntempo": "electronica / downtempo",
  "hiphoprandb": "hip-hop / r'n'b",
  "newclub": "new club",
  "ukdance": "uk dance / grime",
  "housetechno": "house / techno",
  "postpunkwave": "post punk / new wave",
  "altrockpunk": "alternative rock / punk",
  "rock": "rock",
  "metal": "metal",
  "avantgarde": "avant garde",
  "caribbean": "caribbean",
  "latinbrazil": "latin / brazilian",
  "jazz": "jazz",
  "soulrhythm": "soul / rhythm & blues",
  "discoboogie": "disco / boogie",
  "africanmiddleeast": "african / middle eastern",
  "asia": "asia",
  "classicalopera": "classical / opera",
  "other": "other",
};

