import csv, json, urllib.request

tax = json.load(urllib.request.urlopen('https://www.nts.live/api/v2/genres'))
# exact forward map: any NTS top-name or subgenre-name (lowercased) -> top-genre name
fwd = {}
TOPS = []
for g in tax['results']:
    top = g['name']
    TOPS.append(top)
    fwd[top.strip().lower()] = top
    for s in g.get('subgenres', []):
        fwd[s['name'].strip().lower()] = top

T = {t: t for t in TOPS}  # convenience: exact top names
def top(name):  # resolve a partial top label to the real one
    for t in TOPS:
        if t.startswith(name): return t
    raise KeyError(name)

AMBIENT=top('ambient'); ELEC=top('electronica'); HIPHOP=top("hip-hop"); NEWCLUB=top('new club')
UKD=top('uk dance'); HOUSE=top('house'); POSTPUNK=top('post punk'); ALTROCK=top('alternative rock')
ROCK='rock'; METAL='metal'; AVANT=top('avant'); CARIB=top('caribbean'); LATIN=top('latin')
JAZZ='jazz'; SOUL=top('soul'); DISCO=top('disco'); AFRICAN=top('african'); ASIA='asia'
CLASS=top('classical'); OTHER='other'

# hand-map for high-frequency tokens the taxonomy names don't cover verbatim
HAND = {
  'idm':ELEC,'downtempo':ELEC,'future bass':ELEC,'lo-fi beats':ELEC,'lo-fi':ELEC,
  'chillwave':ELEC,'chillstep':ELEC,
  'alternative r&b':SOUL,'r&b':SOUL,'neo soul':SOUL,'indie soul':SOUL,'classic soul':SOUL,
  'quiet storm':SOUL,'motown':SOUL,'retro soul':SOUL,
  'desi':ASIA,'tamil pop':ASIA,'hindi pop':ASIA,'kollywood':ASIA,'telugu pop':ASIA,
  'tamil dance':ASIA,'tollywood':ASIA,'punjabi pop':ASIA,'sufi':ASIA,'kannada pop':ASIA,
  'punjabi hip hop':ASIA,'indian indie':ASIA,'desi hip hop':ASIA,'devotional':ASIA,
  'tamil hip hop':ASIA,'bangla pop':ASIA,'marathi pop':ASIA,'malayalam pop':ASIA,
  'mollywood':ASIA,
  'melodic rap':HIPHOP,'southern hip hop':HIPHOP,'alternative hip hop':HIPHOP,'jazz rap':HIPHOP,
  'east coast hip hop':HIPHOP,'old school hip hop':HIPHOP,'west coast hip hop':HIPHOP,
  'boom bap':HIPHOP,'underground hip hop':HIPHOP,'rage rap':HIPHOP,'lo-fi hip hop':HIPHOP,
  'trap soul':HIPHOP,'crunk':HIPHOP,
  'bass music':UKD,'drumstep':UKD,'breakbeat':HOUSE,'drum and bass':UKD,'uk garage':UKD,
  'liquid funk':UKD,'uk grime':UKD,
  'lo-fi house':HOUSE,'minimal techno':HOUSE,'jazz house':HOUSE,'melodic house':HOUSE,
  'melodic techno':HOUSE,'acid house':HOUSE,
  'nu jazz':JAZZ,'jazz funk':JAZZ,'acid jazz':JAZZ,'experimental jazz':JAZZ,'indie jazz':JAZZ,
  'jazz beats':JAZZ,
  'neo-psychedelic':ALTROCK,'indie':ALTROCK,'alternative rock':ALTROCK,
  'bedroom pop':OTHER,'art pop':OTHER,'baroque pop':OTHER,
  'plunderphonics':AVANT,'electroacoustic':AVANT,'musique concrète':AVANT,
  'afropop':AFRICAN,'afro r&b':AFRICAN,'afroswing':AFRICAN,'afropiano':NEWCLUB,
  'roots reggae':CARIB,
}
fwd.update(HAND)

# scan library tokens, build reverse map top -> sorted set of raw tokens present in data
bucket_tokens = {t: set() for t in TOPS}
tok_count = {}
tot=tagged=0
with open('public/data/masterlist.csv') as f:
    for r in csv.DictReader(f):
        tot+=1
        g=(r.get('Genres') or '').strip()
        if not g: continue
        tagged+=1
        for raw in g.split(','):
            t=raw.strip().lower()
            if not t: continue
            tok_count[t]=tok_count.get(t,0)+1
            if t in fwd: bucket_tokens[fwd[t]].add(t)

covered=0
with open('public/data/masterlist.csv') as f:
    for r in csv.DictReader(f):
        g=(r.get('Genres') or '').strip()
        if not g: continue
        toks={x.strip().lower() for x in g.split(',') if x.strip()}
        if any(x in fwd for x in toks): covered+=1

# emit TS
lines=[]
lines.append("// AUTO-GENERATED by scripts/gen_nts_genre_map.py — do not edit by hand.")
lines.append("// Maps the library's free-text Spotify genre tokens onto NTS's controlled")
lines.append("// top-level vocabulary (nts.live/api/v2/genres). Used to filter the track")
lines.append("// library by NTS genre. Exact taxonomy matches + a hand-map of the")
lines.append("// high-frequency residual. Keys are NTS top-genres; values are the raw")
lines.append("// lowercase tokens (as they appear in the Genres column) that roll up to it.")
lines.append("")
lines.append("export const NTS_GENRES: string[] = [")
for t in TOPS:
    if bucket_tokens[t]:
        lines.append(f"  {json.dumps(t)},")
lines.append("];")
lines.append("")
lines.append("export const NTS_GENRE_TOKENS: Record<string, string[]> = {")
for t in TOPS:
    toks=sorted(bucket_tokens[t])
    if toks:
        lines.append(f"  {json.dumps(t)}: {json.dumps(toks)},")
lines.append("};")
lines.append("")
lines.append("// NTS episode/show genres arrive as subgenre objects whose id is")
lines.append("// `genres-<groupId>-<sub>`. This rolls a groupId up to its top-genre so the")
lines.append("// NTS tab and the track library share one set of filter chips.")
lines.append("export const NTS_GROUP_TO_TOP: Record<string, string> = {")
for g in tax['results']:
    lines.append(f"  {json.dumps(g['id'])}: {json.dumps(g['name'])},")
lines.append("};")
lines.append("")
open('src/lib/nts-genre-map.ts','w').write("\n".join(lines)+"\n")

print(f"coverage: {covered}/{tagged} tagged tracks ({100*covered//tagged}%), {100*covered//tot}% of all {tot}")
print("buckets with tokens:", sum(1 for t in TOPS if bucket_tokens[t]))
print("distinct tokens mapped:", sum(len(bucket_tokens[t]) for t in TOPS))
